# Generated by Django 2.1.1 on 2018-09-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.IntegerField(blank=True)),
                ('rated', models.CharField(blank=True, max_length=16)),
                ('released', models.DateField(blank=True)),
                ('runtime', models.CharField(blank=True, max_length=16)),
                ('genre', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=128)),
                ('writer', models.CharField(blank=True, max_length=128)),
                ('actors', models.TextField(blank=True)),
                ('plot', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('awards', models.TextField(blank=True)),
                ('metascore', models.IntegerField(blank=True)),
                ('imdb_rating', models.FloatField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
